version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
skip_branch_with_pr: true
before_build:
- ps: dotnet restore src\MeepMeep.sln -v Minimal
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
test:
  assemblies:
    only:
      - MeepMeep.UnitTests.dll
deploy:
- provider: NuGet
  server: https://www.myget.org/F/meep-meep/api/v2/package
  api_key:
    secure: Cov0c7H0EvTAcF+4heoatFrtbFVvnz9PR0bTNbDKVTjcN47Vy1k2C3Siep6NsdA7
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: false
- provider: NuGet
  server: https://www.nuget.org/api/v2/package
  api_key:
    secure: RR63qaRziTfBDzeAHNLX/nNGavXrfzgXnSRniyuFgK493SzEw8DUa89bgVZHYSg8
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true
