version: 1.1.{build}
image: Visual Studio 2017
skip_branch_with_pr: true
build_script:
- ps: msbuild src\MeepMeep.sln /t:Restore,Pack /p:Configuration=Release /p:version=$env:APPVEYOR_BUILD_VERSION /p:PackageOutputPath=$env:APPVEYOR_BUILD_FOLDER /p:IncludeSymbols=true /p:IncludeSource=true /v:minimal
artifacts:
- path: '*.nupkg'
deploy:
- provider: NuGet
  server: https://www.myget.org/F/meep-meep/api/v2/package
  symbol_server: https://www.myget.org/F/meep-meep/symbols/api/v2/package
  api_key:
    secure: Cov0c7H0EvTAcF+4heoatFrtbFVvnz9PR0bTNbDKVTjcN47Vy1k2C3Siep6NsdA7
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: false
- provider: NuGet
  server: https://www.nuget.org/api/v2/package
  api_key:
    secure: RR63qaRziTfBDzeAHNLX/nNGavXrfzgXnSRniyuFgK493SzEw8DUa89bgVZHYSg8
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true
