image: Visual Studio 2017
version: 0.2.0.{build}
configuration: Release
skip_branch_with_pr: true
cache:
- src\packages -> **\packages.config
- '%LocalAppData%\NuGet\Cache'
- '%LocalAppData%\NuGet\v3-cache'
before_build:
- ps: appveyor-retry dotnet restore -v Minimal
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
test_script:
- ps: dotnet test "src\tests\MeepMeep.UnitTests"
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  server: https://www.myget.org/F/meep-meep/api/v2/package
  api_key:
    secure: Cov0c7H0EvTAcF+4heoatFrtbFVvnz9PR0bTNbDKVTjcN47Vy1k2C3Siep6NsdA7
  skip_symbols: true
  artifact: '**\*.nupkg'
  on:
    appveyor_repo_tag: false
- provider: NuGet
  server: https://www.nuget.org/api/v2/package
  api_key:
    secure: RR63qaRziTfBDzeAHNLX/nNGavXrfzgXnSRniyuFgK493SzEw8DUa89bgVZHYSg8
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true
